### ISSUE TITLE
Referer url configuration

### ISSUE THREAD

**Issue by dcardin** [cabernetwork/provider_video_m3u#2]
Is it possible to set the Referer URL for the m3u channel? 
My use case will reject the call to the m3u8 if the referer is not set.

**Comment by rocky4546** [comment]
Of course it does.  In the top of the m3u file, add the following

#EXTM3U
#EXT-X-SESSION-DATA:DATA-ID='HEADER',VALUE='{"Referer": "https://sitetoadd.com/", "Origin": "https://sitetoadd.com"}'


You can basically add any header name/value item you need and it will send that when talking to the provider.  I use it quite often, so I know it works well.

**Comment by dcardin** [comment]
Meaning I have to load from a local m3u file instead of a url right ?
Feels simple enough though. Thanks

**Comment by dcardin** [comment]
Alright, so there is something I need to do more, because my m3u(8) comes from an https address, so I cannot add the headers to the file being fetched. Suggestions appreciated!

**Comment by rocky4546** [comment]
use wget or something similar and do an update using sed, nawk or some kind of tool...

**Comment by dcardin** [comment]
The m3u is dynamic, as it's a live feed. Fetching the m3u itself needs a referer to get started
