### ISSUE TITLE
XMLTV File Contains No Program Data

### ISSUE THREAD

**Issue by bobcoup** [cabernetwork/provider_video_m3u#7]
Cabernet Version: 0.9.15.00-RC01
M3U Plugin: 0.1.15

The M3U Plugin is configured with XMLTV enabled and set to get the info from here, https://i.mjh.nz/SamsungTVPlus/gb.xml.gz.

The EPG task appears to run, but all that is in the XMLTV link looks as follows:

<programme start="20240704170000 +0100" stop="20240704180000 +0100" channel="samsung-GBAJ4900006TU">
<title lang="en">Action Movies - Rakuten TV</title>
<desc lang="en">Movies / Not Available</desc>
<length units="minutes">60</length>
<category lang="en">Movies</category>
<previously-shown/>
</programme>
<programme start="20240704180000 +0100" stop="20240704190000 +0100" channel="samsung-GBAJ4900006TU">
<title lang="en">Action Movies - Rakuten TV</title>
<desc lang="en">Movies / Not Available</desc>
<length units="minutes">60</length>
<category lang="en">Movies</category>
<previously-shown/>
</programme>
<programme start="20240704190000 +0100" stop="20240704200000 +0100" channel="samsung-GBAJ4900006TU">
<title lang="en">Action Movies - Rakuten TV</title>
<desc lang="en">Movies / Not Available</desc>
<length units="minutes">60</length>
<category lang="en">Movies</category>
<previously-shown/>
</programme>
<programme start="20240704200000 +0100" stop="20240704210000 +0100" channel="samsung-GBAJ4900006TU">
<title lang="en">Action Movies - Rakuten TV</title>
<desc lang="en">Movies / Not Available</desc>
<length units="minutes">60</length>
<category lang="en">Movies</category>
<previously-shown/>
</programme>
<programme start="20240704210000 +0100" stop="20240704220000 +0100" channel="samsung-GBAJ4900006TU">
<title lang="en">Action Movies - Rakuten TV</title>
<desc lang="en">Movies / Not Available</desc>
<length units="minutes">60</length>
<category lang="en">Movies</category>
<previously-shown/>
</programme>
<programme start="20240704220000 +0100" stop="20240704230000 +0100" channel="samsung-GBAJ4900006TU">
<title lang="en">Action Movies - Rakuten TV</title>
<desc lang="en">Movies / Not Available</desc>
<length units="minutes">60</length>
<category lang="en">Movies</category>
<previously-shown/>

The original gb.xml contains program data.

This issue only seems to have started occuring since 0.1.15.

**Comment by rocky4546** [comment]
The issue is that the Samsung M3U8 file contains multiple channel ids (which is not an issue), but the ids are all different.  Then the xml file contains one of the ids (the tvg-id) and not the "channel-id".  So when Cabernet uses the channel-id, it will not find it in the xml file causing the results you see. Here is the issue.  There is no standard on either the xml or the m3u, so will need to figure out how to let you configure it to apply the id you want when importing the m3u8 file.  The primary default will be tvg-id since that is suppose to be the tv guide channel id.

**Comment by rocky4546** [comment]
Give version 16 a try and let me know if it is working.

**Comment by bobcoup** [comment]
Hello. Version 16 seems to have fixed the issue. Thanks!
